"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.any_pb2
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import zenrock.policy.params_pb2

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class MsgUpdateParams(google.protobuf.message.Message):
    """MsgUpdateParams is the Msg/UpdateParams request type."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    AUTHORITY_FIELD_NUMBER: builtins.int
    PARAMS_FIELD_NUMBER: builtins.int
    authority: builtins.str
    """authority is the address that controls the module (defaults to x/gov unless overwritten)."""
    @property
    def params(self) -> zenrock.policy.params_pb2.Params:
        """params defines the module parameters to update.

        NOTE: All parameters must be supplied.
        """

    def __init__(
        self,
        *,
        authority: builtins.str = ...,
        params: zenrock.policy.params_pb2.Params | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["params", b"params"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["authority", b"authority", "params", b"params"]) -> None: ...

global___MsgUpdateParams = MsgUpdateParams

@typing.final
class MsgUpdateParamsResponse(google.protobuf.message.Message):
    """MsgUpdateParamsResponse defines the response structure for executing a
    MsgUpdateParams message.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgUpdateParamsResponse = MsgUpdateParamsResponse

@typing.final
class MsgNewPolicy(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CREATOR_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    POLICY_FIELD_NUMBER: builtins.int
    creator: builtins.str
    name: builtins.str
    @property
    def policy(self) -> google.protobuf.any_pb2.Any: ...
    def __init__(
        self,
        *,
        creator: builtins.str = ...,
        name: builtins.str = ...,
        policy: google.protobuf.any_pb2.Any | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["policy", b"policy"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["creator", b"creator", "name", b"name", "policy", b"policy"]) -> None: ...

global___MsgNewPolicy = MsgNewPolicy

@typing.final
class MsgNewPolicyResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    id: builtins.int
    def __init__(
        self,
        *,
        id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id"]) -> None: ...

global___MsgNewPolicyResponse = MsgNewPolicyResponse

@typing.final
class MsgRevokeAction(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CREATOR_FIELD_NUMBER: builtins.int
    ACTION_TYPE_FIELD_NUMBER: builtins.int
    ACTION_ID_FIELD_NUMBER: builtins.int
    creator: builtins.str
    action_type: builtins.str
    action_id: builtins.int
    def __init__(
        self,
        *,
        creator: builtins.str = ...,
        action_type: builtins.str = ...,
        action_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["action_id", b"action_id", "action_type", b"action_type", "creator", b"creator"]) -> None: ...

global___MsgRevokeAction = MsgRevokeAction

@typing.final
class MsgRevokeActionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgRevokeActionResponse = MsgRevokeActionResponse

@typing.final
class MsgApproveAction(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CREATOR_FIELD_NUMBER: builtins.int
    ACTION_TYPE_FIELD_NUMBER: builtins.int
    ACTION_ID_FIELD_NUMBER: builtins.int
    ADDITIONAL_SIGNATURES_FIELD_NUMBER: builtins.int
    creator: builtins.str
    action_type: builtins.str
    action_id: builtins.int
    @property
    def additional_signatures(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.any_pb2.Any]: ...
    def __init__(
        self,
        *,
        creator: builtins.str = ...,
        action_type: builtins.str = ...,
        action_id: builtins.int = ...,
        additional_signatures: collections.abc.Iterable[google.protobuf.any_pb2.Any] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["action_id", b"action_id", "action_type", b"action_type", "additional_signatures", b"additional_signatures", "creator", b"creator"]) -> None: ...

global___MsgApproveAction = MsgApproveAction

@typing.final
class MsgApproveActionResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    status: builtins.str
    def __init__(
        self,
        *,
        status: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status", b"status"]) -> None: ...

global___MsgApproveActionResponse = MsgApproveActionResponse

@typing.final
class MsgAddSignMethod(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CREATOR_FIELD_NUMBER: builtins.int
    CONFIG_FIELD_NUMBER: builtins.int
    creator: builtins.str
    @property
    def config(self) -> google.protobuf.any_pb2.Any: ...
    def __init__(
        self,
        *,
        creator: builtins.str = ...,
        config: google.protobuf.any_pb2.Any | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["config", b"config"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["config", b"config", "creator", b"creator"]) -> None: ...

global___MsgAddSignMethod = MsgAddSignMethod

@typing.final
class MsgAddSignMethodResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgAddSignMethodResponse = MsgAddSignMethodResponse

@typing.final
class MsgRemoveSignMethod(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CREATOR_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    creator: builtins.str
    id: builtins.str
    def __init__(
        self,
        *,
        creator: builtins.str = ...,
        id: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["creator", b"creator", "id", b"id"]) -> None: ...

global___MsgRemoveSignMethod = MsgRemoveSignMethod

@typing.final
class MsgRemoveSignMethodResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___MsgRemoveSignMethodResponse = MsgRemoveSignMethodResponse
